-- CREATE TABLE IF NOT EXISTS NOBEL_WIN (
-- YEAR INTEGER,
-- SUBJECT TEXT,
-- WINNER TEXT,
-- COUNTRY TEXT,
-- CATEGORY TEXT
-- );

-- INSERT INTO NOBEL_WIN (YEAR,SUBJECT,WINNER,COUNTRY,CATEGORY) VALUES
-- (1970,'PHYSICS','HANNES ALFVIN','SWEDEN','SCIENTIST'),
-- (1970,'PHYSICS','LOUIS NEEL','FRANCE','SCIENTIST'),
-- (1971,'PHYSICS','PAUL HAYDEN','UNITED STATES','SCIENTIST'),
-- (1971,'CHEMISTRY','TAKURO ITO','JAPAN','SCIENTIST'),
-- (1972,'LITERATURE','ABRAR AHMED','BANGLADESH','LUIGIST'),
-- (1972,'ECONOMICS','JOSEPH VLADISOV','RUSSIA','ECONOMIST'),
-- (1973,'BIOLOGY','LEE BYEONG-JI','SOUTH KOREA','BIOLOGIST'),
-- (1973,'PHYSIOLOGY','BALJEET SINGH','INDIA','PHYSIOLOGIST'),
-- (1974,'NUCLEAR PHYSICS','LEO EMILIANO','ITALY','SCIENTIST'),
-- (1974,'PHYSICS','MUSA IMRAN','PAKISTAN','SCIENTIST'),
-- (1975,'CHEMISTRY','MARTIN DAKILA','PHILIPPINES','SCIENTIST'),
-- (1975,'PHYSICS','WUHAO-LOO','CHINA','SCIENTIST');

SELECT * FROM NOBEL_WIN WHERE CATEGORY LIKE "S%"